# the purpose of this github action is to test that cppcheck source code can be compiled using old gcc versions.
# the gcc images we use here are copied from the official gcc images on docker hub

name: gcc-versions

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        image: ["ghcr.io/cppcheck-opensource/gcc:5.4", "ghcr.io/cppcheck-opensource/gcc:6.5", "ghcr.io/cppcheck-opensource/gcc:7.5", "ghcr.io/cppcheck-opensource/gcc:8.5", "ghcr.io/cppcheck-opensource/gcc:9.5"]
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build cppcheck
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src ${{ matrix.image }} make -j$(nproc) CXXOPTS="-Werror" test
